# Site wide configuration

title: teepee
locale: en_US
description: 'Get the most out of your APIs... from the shell!'
logo: teepee-sfumati.png
search: true
url: http://github.polettix.it/teepee

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..4
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Flavio Poletti
  avatar: flavio-self-color.png
  email: flavio@polettix.it
  disqus-shortname: polettix
  twitter: polettix
  github: polettix
  stackexchange: http://stackexchange.com/users/4784505/polettix
  linkedin: flaviopoletti
  pinterest: polettix
