# Site settings
title: teepee
email: flavio@polettix.it
description: >
    Get the most out of your APIs... from the shell!
baseurl: "/teepee"
url: "http://github.polettix.it/"
twitter_username: polettix
github_username:  polettix

# Build settings
markdown: kramdown
