# Site settings
title: teepee
email: flavio@polettix.it
description: >
    TeePee articles and stuff
baseurl: "/teepee/"
url: "http://github.polettix.it/"
twitter_username: polettix
github_username:  polettix

# Build settings
markdown: kramdown
